# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aRFxPyihdDXM6PqwHSG9s_VF0JS7hFmA
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# %pip install pymorphy3
# %pip install wordcloud
# %pip install catboost

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import nltk
import warnings
import joblib
import ast

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import MaxAbsScaler
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.ensemble import VotingClassifier
from catboost import CatBoostClassifier

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from pymorphy3 import MorphAnalyzer
from wordcloud import WordCloud

from collections import Counter

warnings.filterwarnings("ignore", category=FutureWarning)

"""# Предобработка текстов"""

df = pd.read_csv('dataset.csv')

df.info()

df.duplicated().sum()

"""> дубликатов нет!

Почистим датасет от пустых или слишком коротких текстов
"""

df = df.dropna(subset=['content'])

short_texts = df['content'].apply(lambda x: len(str(x).strip()) < 80).sum()
short_texts

"""> совсем коротких текстов нет

Почистим от мусора и нормализуем текст
"""

def clean_text(text):

    text = str(text).lower() # нижний регистр

    text = re.sub(r'<[^>]+>', '', text) # чистим от html-тегов
    text = re.sub(r'https?://\S+|www\.\S+', '', text) # чистим от url
    text = re.sub(r'[^а-яё\s]', '', text) # убираем знаки и цифры
    text = re.sub(r'\s+', ' ', text).strip() # убираем лишние пробелы

    return text

df['content'] = df['content'].apply(clean_text)

"""Токенизируем + лемматизируем"""

nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
stop_words = set(stopwords.words('russian'))

morph = MorphAnalyzer()

df['tokens'] = df['content'].apply(word_tokenize)
df['tokens'] = df['tokens'].apply(
    lambda x: [morph.parse(token)[0].normal_form for token in x])

df.to_csv('lemmatized_dataset.csv', index=False)

df = pd.read_csv('lemmatized_dataset.csv')
df['tokens'] = df['tokens'].apply(ast.literal_eval)

df.head()

df['tokens'].sample(6)

df['tokens'] = df['tokens'].apply(
    lambda x: [token for token in x if token not in stop_words and len(token) > 1])

"""Попробуем найти мусорные токены среди самых частых"""

all_tokens = [token for sublist in df['tokens'] for token in sublist]
token_counts = Counter(all_tokens)

pd.DataFrame(token_counts.most_common(20))

"""> Мусорными кажутся все"""

most_common_tokens = [token for token, count in token_counts.most_common(20)]
stop_words.update(most_common_tokens)

df['tokens'] = df['tokens'].apply(
    lambda x: [token for token in x if token not in stop_words])

all_tokens = [token for sublist in df['tokens'] for token in sublist]
token_counts = Counter(all_tokens)

pd.DataFrame(token_counts.most_common(20))

"""Найдем для каждого значения topic топ-10 популярных токенов и почистим пересечения (считаем, что если токен встречается часто в каждой теме - тогда он мусорный)"""

top_tokens_by_topic = {}

for topic in df['topic'].unique():
    topic_tokens = []
    for tokens in df[df['topic'] == topic]['tokens']:
        topic_tokens.extend(tokens)

    token_counts = Counter(topic_tokens)
    top_tokens = [token for token, count in token_counts.most_common(10)]
    top_tokens_by_topic[topic] = top_tokens

top_tokens_by_topic

token_sets = [set(tokens) for tokens in top_tokens_by_topic.values()]

# Находим пересечение всех множеств
common_tokens = set.intersection(*token_sets)

print("Общие токены для всех topics:")
print(common_tokens)

"""> таких токенов нет  :("""

df.to_csv('lemmatized_dataset.csv', index=False)

"""Выведем вордклауды для каждой темы"""

token_freq_by_topic = {}

for topic in df['topic'].unique():
    topic_tokens = []
    for tokens in df[df['topic'] == topic]['tokens']:
        topic_tokens.extend(tokens)

    token_counts = Counter(topic_tokens)
    token_freq_by_topic[topic] = dict(token_counts.most_common(100))

n_topics = 9
cols = 2
rows = (n_topics + 1) // 2

topic_names = {
    0: 'Общество/Россия',
    1: 'Экономика',
    2: 'Силовые структуры',
    3: 'Бывший СССР',
    4: 'Спорт',
    5: 'Забота о себе',
    6: 'Строительство',
    7: 'Туризм/Путешествия',
    8: 'Наука и техника'
}

fig, axes = plt.subplots(rows, cols, figsize=(14, 5 * rows))
axes = axes.flatten()

for idx, topic in enumerate(token_freq_by_topic.keys()):
    wordcloud = WordCloud(
        width=800,
        height=400,
        background_color='white',
        colormap='viridis',
        max_words=50
    ).generate_from_frequencies(token_freq_by_topic[topic])

    axes[idx].imshow(wordcloud, interpolation='bilinear')
    axes[idx].set_title(f'{topic_names.get(topic, topic)}', fontsize=14, fontweight='bold')
    axes[idx].axis('off')

# Скрываем лишние сабплоты
for idx in range(n_topics, len(axes)):
    axes[idx].axis('off')

plt.tight_layout()
plt.show()

"""# Векторизация + обучение моделей"""

df = pd.read_csv('lemmatized_dataset.csv')
df['tokens'] = df['tokens'].apply(ast.literal_eval)
df['clean_text'] = df['tokens'].apply(' '.join)

df.head()

X = df['clean_text']
y = df['topic']

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.25,
                                                    random_state=42,
                                                    stratify=y)

X_train.shape, X_test.shape

"""Мне известны 2 метода векторизации - Bag of Words и TF-IDF, поэтому использовать будем их

- BoW - просто подсчитывает частоту слов в документе, создавая вектор, где каждое слово имеет одинаковый вес

- TF-IDF учитывает частоту слов, но дополнительно штрафует веса токенов, которые встречаются во многих текстах (чем чаще слово встречается в одном документе и реже в других, тем выше его вес)

Пайплайн №1: Bag of Words + LogReg
"""

bow_logreg = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('clf', LogisticRegression(max_iter=1000, random_state=42))
])

bow_logreg.fit(X_train, y_train)

y_pred_bow = bow_logreg.predict(X_test)
acc_bow = accuracy_score(y_test, y_pred_bow)
print(f"Test Accuracy: {acc_bow:.4f}")

bow_logreg = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('clf', LogisticRegression(max_iter=1000, random_state=42))
])

param_grid_bow = {
    'vectorizer__max_features': [10000],
    'vectorizer__ngram_range': [(1, 2)],
    'vectorizer__min_df': [2],
    'vectorizer__max_df': [0.95],

    'clf__C': [0.01, 0.05, 0.1],
}

grid_bow = GridSearchCV(
    bow_logreg,
    param_grid_bow,
    cv=3,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

grid_bow.fit(X_train, y_train)

print(f"Accuracy: {grid_bow.best_score_:.4f}")

grid_bow.best_params_

y_pred_bow = grid_bow.predict(X_test)
acc_bow = accuracy_score(y_test, y_pred_bow)
print(f"Test Accuracy: {acc_bow:.4f}")

"""Пайплайн №2: TF-IDF + LogReg"""

tfidf_logreg = Pipeline([
    ('vectorizer', TfidfVectorizer()),
    ('clf', LogisticRegression(max_iter=1000, random_state=42))
])

param_grid_tfidf = {
    'vectorizer__max_features': [10000],
    'vectorizer__ngram_range': [(1, 2)],
    'vectorizer__min_df': [2],
    'vectorizer__max_df': [0.95],
    'vectorizer__sublinear_tf': [True],

    'clf__C': [4, 5, 7]
}

grid_tfidf = GridSearchCV(
    tfidf_logreg,
    param_grid_tfidf,
    cv=3,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

grid_tfidf.fit(X_train, y_train)

print(f"Accuracy: {grid_tfidf.best_score_:.4f}")

joblib.dump(grid_tfidf.best_params_, 'tfidf_params.joblib')
grid_tfidf.best_params_

y_pred_tfidf = grid_tfidf.predict(X_test)
acc_tfidf = accuracy_score(y_test, y_pred_tfidf)
print(f"Test Accuracy: {acc_tfidf:.4f}")

"""Пайплайн №3: TF-IDF + CatBoost"""

pipe_cb = Pipeline([
    ('vectorizer', TfidfVectorizer()),
    ('clf', CatBoostClassifier(
        verbose=0,
        random_state=42,
        task_type='CPU'
    ))
])

pipe_cb.fit(X_train, y_train)

y_pred_bow = pipe_cb.predict(X_test)
acc_bow = accuracy_score(y_test, y_pred_bow)
print(f"Test Accuracy: {acc_bow:.4f}")

"""# Финальная модель"""

best_params = joblib.load('tfidf_params.joblib')
print(f"Лучшие параметры: {best_params}")

final_model = Pipeline([
    ('vectorizer', TfidfVectorizer(
        max_features=best_params['vectorizer__max_features'],
        ngram_range=best_params['vectorizer__ngram_range'],
        min_df=best_params['vectorizer__min_df'],
        max_df=best_params['vectorizer__max_df'],
        sublinear_tf=best_params['vectorizer__sublinear_tf']
    )),
    ('clf', LogisticRegression(
        C=best_params['clf__C'],
        max_iter=1000,
        random_state=42
    ))
])

final_model.fit(X, y)

"""Предобработка инпута для Kaggle"""

X_kaggle = pd.read_csv('test.news.csv')

X_kaggle['content'] = X_kaggle['content'].apply(clean_text)
X_kaggle['tokens'] = X_kaggle['content'].apply(word_tokenize)
X_kaggle['tokens'] = X_kaggle['tokens'].apply(
    lambda x: token for token in x if token not in stop_words and len(token) > 1
)

X_kaggle.to_csv('kaggle_tokens.csv', index=False)

X_kaggle = pd.read_csv('kaggle_tokens.csv')
X_kaggle['tokens'] = X_kaggle['tokens'].apply(ast.literal_eval)
X_kaggle['clean_text'] = X_kaggle['tokens'].apply(' '.join)
X_kaggle.head()

"""Получение предсказаний для Kaggle"""

kaggle_pred = final_model.predict(X_kaggle['clean_text'])

submission = pd.DataFrame({
    'topic': kaggle_pred,
    'index': range(len(kaggle_pred))
})
submission.to_csv('pred_3.csv', index=False)